---
- hosts: deploy_node
  name: Install Tempest on BME
  tasks:
    - name: Install tempest on containers
      command: /usr/local/bin/openstack-ansible os-tempest-install.yml
      args:
        chdir: /opt/openstack-ansible/playbooks/

    - name: Configure and run tempest tests
      command: /usr/local/bin/ansible utility_all -i /opt/openstack-ansible/playbooks/inventory -m script -a "scripts/bme_tempest_run.sh" 
