---
- hosts: deploy_node
  name: Install Tempest on BME
  tasks:
    - name: Install tempest on containers
      command: /usr/local/bin/openstack-ansible os-tempest-install.yml
      args:
        chdir: /opt/openstack-ansible/playbooks/

    - name: Transfer tempest script to utility containers
      command: /usr/local/bin/ansible utility_all -i /opt/openstack-ansible/playbooks/inventory -m copy -a "src=/root/bme_tempest_run.sh dest=/root/bme_tempest_run.sh"
  
    - name: Run tempest on utility nodes
      command: /usr/local/bin/ansible utility_all -i /opt/openstack-ansible/playbooks/inventory -m shell -a "/bin/bash /root/bme_tempest_run.sh"
