---
- hosts: deploy_node
  name: Install persistent resource tests
  tasks:
    - name: Clone git repo persistent-resources-tests
      command: /usr/local/bin/ansible utility_all -i /opt/openstack-ansible/playbooks/inventory -m shell -a "git clone https://github.com/osic/persistent-resources-tests.git /root/persistent-resources-tests"

    - name: install persistent-resources-tests
      command: /usr/local/bin/ansible utility_all -i /opt/openstack-ansible/playbooks/inventory -m shell -a "pip install /root/persistent-resources-tests"

    - name: Clone git repo persistent-resources-tests
      command: /usr/local/bin/ansible utility_all -i /opt/openstack-ansible/playbooks/inventory -m shell -a "git clone https://github.com/osic/persistent-resources-tests-parse.git /root/persistent-resources-tests-parse"

    - name: install persistent-resources-tests-parse
      command: /usr/local/bin/ansible utility_all -i /opt/openstack-ansible/playbooks/inventory -m shell -a "pip install /root/persistent-resources-tests-parse"

    - name: Transfer tempest script to utility containers
      command: /usr/local/bin/ansible utility_all -i /opt/openstack-ansible/playbooks/inventory -m copy -a "src=/root/bme_tempest_run.sh dest=/root/bme_tempest_run.sh"

    - name: Run persistent tests
      command: /usr/local/bin/ansible utility_all -i /opt/openstack-ansible/playbooks/inventory -m shell -a "/bin/bash /root/bme_tempest_run.sh persistent-verify persistent-resources-tests"
    - name: Run persistent tests
      command: /usr/local/bin/ansible utility_all -i /opt/openstack-ansible/playbooks/inventory -m shell -a "/bin/bash /root/bme_tempest_run.sh persistent-clean persistent-resources-tests"

    - name: Run persistent resources tests parse
      command: cd /root/subunit/persistent-resources-tests/ &&  resource-parse --u . > /root/output/persistent_resource.txt && rm *.csv
